-- MySQL Script generated by MySQL Workbench
-- 09/05/16 07:26:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bikes4free
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bikes4free
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bikes4free` DEFAULT CHARACTER SET utf8 ;
USE `bikes4free` ;

-- -----------------------------------------------------
-- Table `bikes4free`.`tipobicicleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikes4free`.`tipobicicleta` (
  `idtipobicicleta` INT NOT NULL,
  `nombretipobicicleta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipobicicleta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikes4free`.`bicicleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikes4free`.`bicicleta` (
  `idbicicleta` INT NOT NULL,
  `tipobicicleta_idtipobicicleta` INT NOT NULL,
  PRIMARY KEY (`idbicicleta`),
  INDEX `fk_bicicleta_tipobicicleta_idx` (`tipobicicleta_idtipobicicleta` ASC),
  CONSTRAINT `fk_bicicleta_tipobicicleta`
    FOREIGN KEY (`tipobicicleta_idtipobicicleta`)
    REFERENCES `bikes4free`.`tipobicicleta` (`idtipobicicleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikes4free`.`tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikes4free`.`tipousuario` (
  `idtipousuario` INT NOT NULL,
  `nombretipousuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipousuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikes4free`.`puntoderetorno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikes4free`.`puntoderetorno` (
  `idpuntoderetorno` INT NOT NULL,
  `nombrepuntoderetorno` VARCHAR(45) NULL,
  PRIMARY KEY (`idpuntoderetorno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikes4free`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikes4free`.`reserva` (
  `idreserva` INT NOT NULL,
  `bicicleta_idbicicleta` INT NOT NULL,
  `puntoderetorno_idpuntoderetorno` INT NOT NULL,
  `puntoderetorno_idpuntoderetorno1` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time`  NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_reserva_bicicleta1_idx` (`bicicleta_idbicicleta` ASC),
  INDEX `fk_reserva_puntoderetorno1_idx` (`puntoderetorno_idpuntoderetorno` ASC),
  INDEX `fk_reserva_puntoderetorno2_idx` (`puntoderetorno_idpuntoderetorno1` ASC),
  INDEX `fk_reserva_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_reserva_bicicleta1`
    FOREIGN KEY (`bicicleta_idbicicleta`)
    REFERENCES `bikes4free`.`bicicleta` (`idbicicleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_puntoderetorno1`
    FOREIGN KEY (`puntoderetorno_idpuntoderetorno`)
    REFERENCES `bikes4free`.`puntoderetorno` (`idpuntoderetorno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_puntoderetorno2`
    FOREIGN KEY (`puntoderetorno_idpuntoderetorno1`)
    REFERENCES `bikes4free`.`puntoderetorno` (`idpuntoderetorno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bikes4free`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikes4free`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikes4free`.`usuario` (
  `idusuario` INT NOT NULL,
  `tipousuario_idtipousuario` INT NOT NULL,
  `reserva_idreserva` INT NOT NULL,
  `username` (16) NOT NULL,
  `email` (255) NULL,
  `password` (32) NOT NULL,
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_tipousuario1_idx` (`tipousuario_idtipousuario` ASC),
  INDEX `fk_usuario_reserva1_idx` (`reserva_idreserva` ASC),
  CONSTRAINT `fk_usuario_tipousuario1`
    FOREIGN KEY (`tipousuario_idtipousuario`)
    REFERENCES `bikes4free`.`tipousuario` (`idtipousuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_reserva1`
    FOREIGN KEY (`reserva_idreserva`)
    REFERENCES `bikes4free`.`reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikes4free`.`multa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikes4free`.`multa` (
  `idmulta` INT NOT NULL,
  `nombremulta` VARCHAR(45) NULL,
  `preciomulta` INT NULL,
  PRIMARY KEY (`idmulta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bikes4free`.`reserva_has_multa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bikes4free`.`reserva_has_multa` (
  `reserva_idreserva` INT NOT NULL,
  `multa_idmulta` INT NOT NULL,
  PRIMARY KEY (`reserva_idreserva`, `multa_idmulta`),
  INDEX `fk_reserva_has_multa_multa1_idx` (`multa_idmulta` ASC),
  INDEX `fk_reserva_has_multa_reserva1_idx` (`reserva_idreserva` ASC),
  CONSTRAINT `fk_reserva_has_multa_reserva1`
    FOREIGN KEY (`reserva_idreserva`)
    REFERENCES `bikes4free`.`reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_has_multa_multa1`
    FOREIGN KEY (`multa_idmulta`)
    REFERENCES `bikes4free`.`multa` (`idmulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
